apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-code
  labels:
    app: sample-code
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-code
  template:
    metadata:
      labels:
        app: sample-code
    spec:
      containers:
        - name: sample-code
          image: sonbarse17/sample-code:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
