apiVersion: v1
kind: Service
metadata:
  name: sample-python-service
  labels:
    app: sample-code
spec:
  type: ClusterIP
  selector:
    app: sample-code
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
