name: Project DevSecOps Pipeline

on:
  push:
    branches:
      - feature-branch
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: write
  packages: write

jobs:
  run-reusable-pipeline:
    uses: sonbarse17/reusable-workflow/.github/workflows/reusable-ci.yml@main
    with:
      python_version: '3.12'
      enable_code_scanning: true
      enable_sonar_scan: false
      enable_owasp_scan: true
      enable_iac_scan: false
      enable_secret_scan: true
      enable_docker_build: true
      docker_registry: 'docker.io'
      docker_image_name: 'sonbarse17/sample-code'
      enable_k8s_deploy: true
      k8s_manifest_dir: 'k8s/'
      enable_dast_scan: true
      dast_target_url: 'http://sample-python-service.default.svc.cluster.local'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
