name: DevOps Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select Branch'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - release
          - feature
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - prod

permissions:
  contents: read
  actions: read
  security-events: write
  packages: write

jobs:
  run-reusable-pipeline:
    uses: sonbarse17/reusable-devops-workflow/.github/workflows/reusable-pipeline.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      image_name: 'sonbarse17/sample-code'
      registry: 'docker.io'
      k8s_cluster: 'k8s-cluster'
      k8s_namespace: 'default'
      k8s_server: 'https://kubernetes-api-server.example.com'
      deploy_method: 'kubectl'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
